In [1]:
import tensorflow as tf

In [2]:
# 레이어를 보면 알겠지만 input값은 사실 지정하지 않아도 된다. 하지만 정교한 구성이 필요한 경우 설정할 수 있다.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))
layer1 = tf.keras.layers.Dense(10)

In [3]:
layer(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [4]:
layer1(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [5]:
# 레이어의 가중치와 변수를 직접 확인해본다.
print('weight : \n',layer.variables)
print('bias : \n',layer.bias)

weight : 
 [<tf.Variable 'dense/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.00699615, -0.21194065,  0.06760269,  0.00884181, -0.32683563,
        -0.30079946, -0.32668182,  0.26408577,  0.4059562 , -0.08635545],
       [ 0.55939144,  0.00762933, -0.0510518 , -0.44223922,  0.6283284 ,
         0.31063682,  0.60145324, -0.46580246,  0.2789551 , -0.44613004],
       [ 0.11100733, -0.3755262 , -0.499754  ,  0.29806262,  0.30382007,
         0.6179438 , -0.37545004,  0.07311946,  0.6050014 , -0.09684539],
       [ 0.5476704 , -0.21325415, -0.1471135 , -0.58584297, -0.37854394,
        -0.47998884,  0.47219783, -0.25691938, -0.29524562, -0.5389058 ],
       [-0.4424336 ,  0.19308114,  0.26263368,  0.6168162 , -0.37285212,
         0.05245036,  0.46826428,  0.3654529 ,  0.04287189, -0.0317995 ]],
      dtype=float32)>, <tf.Variable 'dense/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]
bias : 
 <tf.Variable 'dense/bias:0' 

## 사용자 지정 레이어 구현
 - \__init__ 은 여기서 모든 입력을 초기화하는 함수이다.
 - build는 입력 텐서의 형상을 알고 나머지 초기화 작업을 수행한다.
 - call은 순방향 계산을 수행한다.
 

In [6]:
class mydenselayer(tf.keras.layers.Layer):
    def __init__(self, num_ouputs):
        super(mydenselayer, self).__init__()
        self.num_ouputs = num_ouputs
    
    def build(self, input_shape):
        self.kernel = self.add_weight('kernel',
                                     shape = [int(input_shape[-1]), self.num_ouputs]
        )

    def call(self, inputs):
        return tf.matmul(inputs, self.kernel)

layer = mydenselayer(10)

In [7]:
layer(tf.zeros([10,5]))

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
layer.kernel

<tf.Variable 'mydenselayer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[ 0.5229036 , -0.14442208, -0.31250885, -0.35773337, -0.04919362,
        -0.31135213, -0.34852603,  0.19484538,  0.55719894, -0.34845984],
       [-0.3211967 , -0.15837777,  0.41921157, -0.5516669 , -0.5442701 ,
         0.24282181, -0.4336055 ,  0.02412355, -0.58794725,  0.2660156 ],
       [-0.5018204 , -0.25657648,  0.04708499, -0.55307335, -0.5402599 ,
         0.60254496,  0.25030655,  0.25766003,  0.49252337, -0.579391  ],
       [ 0.6169397 , -0.23985714,  0.23962355, -0.46274143,  0.05290604,
        -0.17597681,  0.39767605, -0.00555992,  0.46505016, -0.6177916 ],
       [-0.4937167 , -0.17223108,  0.47867686, -0.24570593, -0.02354801,
        -0.5106081 ,  0.5573916 , -0.41532415, -0.27221408,  0.50318736]],
      dtype=float32)>

In [9]:
[k.name for k in layer.trainable_weights]

['mydenselayer/kernel:0']

## 합성 레이어
### keras.Model 은 다음과 같은 메서드가 필요할 때 상속합니다.
 - Model.fit, Model.evaluate, Model.save
<br>아래의 예시는 Resnet 볼록입니다.


In [37]:
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, model_name, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__(name = model_name)
        filters1, filters2, filters3 = filters

        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()

        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()

        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()

    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2b(x)
        x = self.bn2b(x, training = training)
        x = tf.nn.relu(x)

        x = self.conv2c(x)
        x = self.bn2c(x, training = training)
        
        x += input_tensor
        return tf.nn.relu(x)

block = ResnetIdentityBlock('test', 1, [1, 2, 3])

In [38]:
block.layers

In [39]:
_ = block(tf.zeros([1,2,3,3]))

In [40]:
len(block.variables)

18

In [41]:
block.summary()

Model: "test"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_12 (Conv2D)          multiple                  4         
                                                                 
 batch_normalization_12 (Bat  multiple                 4         
 chNormalization)                                                
                                                                 
 conv2d_13 (Conv2D)          multiple                  4         
                                                                 
 batch_normalization_13 (Bat  multiple                 8         
 chNormalization)                                                
                                                                 
 conv2d_14 (Conv2D)          multiple                  9         
                                                                 
 batch_normalization_14 (Bat  multiple                 12     

대부분의 경우 많은 레이어를 구성하는 모델은 단순히 한 레이어를 차례로 호출한다. 이것은 다음과 같이 간단한 코드로 표현이 가능해진다.

In [42]:
my_seq = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1,1), input_shape=(None, None, 3)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(3, (1, 1)),
    tf.keras.layers.BatchNormalization()
])

my_seq(tf.zeros([1, 2 ,3 ,3]))

<tf.Tensor: shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [43]:
my_seq.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_15 (Conv2D)          (None, None, None, 1)     4         
                                                                 
 batch_normalization_15 (Bat  (None, None, None, 1)    4         
 chNormalization)                                                
                                                                 
 conv2d_16 (Conv2D)          (None, None, None, 2)     4         
                                                                 
 batch_normalization_16 (Bat  (None, None, None, 2)    8         
 chNormalization)                                                
                                                                 
 conv2d_17 (Conv2D)          (None, None, None, 3)     9         
                                                                 
 batch_normalization_17 (Bat  (None, None, None, 3)    1